### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by serjo77** [logicmonitor/lm_python#12]
DEBUG:root:Instantiating Host object
DEBUG:root:Instantiating LogicMonitor object
DEBUG:root:Hostname is 10.215.253.254
DEBUG:root:Display name is ssh-proxy.prod-euc1
DEBUG:root:Attempting to find host by displayname ssh-proxy.prod-euc1
DEBUG:root:Running LogicMonitor.get_host_by_displayname...
DEBUG:root:Looking for displayname ssh-proxy.prod-euc1
DEBUG:root:Making RPC call to 'getHost'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call failed
DEBUG:root:{u'status': 1007, u'errmsg': u'No such host'}
DEBUG:root:Host not found by displayname
DEBUG:root:Collector specified is control1.prod-euc1.jfrog.local
DEBUG:root:Running LogicMonitor.get_collector_by_description...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Looking for collector with description control1.prod-euc1.jfrog.local
DEBUG:root:Collector match found
DEBUG:root:Attempting to find host by hostname 10.215.253.254
DEBUG:root:Running LogicMonitor.get_host_by_hostname...
DEBUG:root:Looking for hostname 10.215.253.254
DEBUG:root:Making RPC call to 'getHosts'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
Traceback (most recent call last):
  File "./device_add.py", line 77, in <module>
    main()
  File "./device_add.py", line 71, in main
    h = Host(params)
  File "/usr/local/lib/python2.7/dist-packages/logicmonitor_core/Host.py", line 66, in __init__
    info = self.get_host_by_hostname(self.hostname, self.collector)
  File "/usr/local/lib/python2.7/dist-packages/logicmonitor_core/LogicMonitor.py", line 121, in get_host_by_hostname
    " and collector " + collector["id"])
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by woz5999** [comment]
Thanks for filing this issue. I added a fix and release a new version of this module. You can run pip update on logicmonitor_core to pull the latest version logicmonitor_core-1.0.7.4
