### ISSUE TITLE
RPC not available

### ISSUE THREAD

**Issue by newtcv** [logicmonitor/lm_python#20]
RPC not available any more.

**Comment by skt44** [comment]
Hi @newtcv - Our RPC API is still available. It's disabled by default for newer LogicMonitor accounts, but we can have it enabled for your account if desired. We're working on a REST API based replacement for lm_python, and will ensure the release of this replacement before making the RPC API unavailable. Thanks!

**Comment by newtcv** [comment]
Great. How do I send my data to you to enable RPC?

**Comment by woz5999** [comment]
I think the best way is to create a support ticket from your portal.

**Comment by newtcv** [comment]
I already tried to open a ticket. The answer was to hire the development of a solution.

![captura de tela de 2018-04-10 16-56-22](https://user-images.githubusercontent.com/2058978/38580430-50ee2bc0-3ce0-11e8-8f06-5119ca2e591d.png)

**Comment by woz5999** [comment]
That's unfortunate. Perhaps they misunderstood or didn't realize they had the ability to re-enable that feature for you. If you're comfortable telling me your portal name, I can enable it for you.

**Comment by woz5999** [comment]
@newtcv I've enabled the RPC API in your account. Please note that the RPC API is deprecated and will eventually be disabled entirely. These scripts are no longer supported and are provided as-is and will eventually be supplanted by a new SDK leveraging our REST api.
